### PR TITLE
fixed table rendering error

### PR DESCRIPTION
**Pull request by lauranovich**
Table was not rendered correctly

### CODE REVIEW

**Comment by sitano** [comment]
@lauranovich please fix the conflict : go/docs/getting_started.md

**Comment by lauranovich** [comment]
@sitano  I don't have permission to fix it

**Comment by sitano** [comment]
@lauranovich you have too old master. you must create a new feature branch and rebase it on top of the latest master.

**Comment by lauranovich** [comment]
ok I'll send a new PR, after I resync

**Comment by lauranovich** [comment]
@sitano Here is the odd thing when I look in Git, I see the table looks fine
when I look at the github page it is not, I do not know why

**Pull request closed without merging**
