### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by dgarcia360**
Updates the theme and config file to match other documentation projects.

### CODE REVIEW

**Comment by sitano** [comment]
@dgarcia360 shall we merge it or better wait for @larisau review?

**Comment by dgarcia360** [comment]
@sitano I'd prefer to get the ok from Laura.

**Comment by lauranovich** [comment]
Hi Ivan - the rationale is this
each project needs a 404.html file so that if the content is not found you get a cute page that says the Scylla Monster ate your page.
For consistency, we need all projects to use the same file and not the default one which we had previously.

**Comment by lauranovich** [comment]
@sitano  have you tested it?
If so and it builds you can merge it 
if not, I need to build it and check

**Comment by sitano** [comment]
> @sitano have you tested it?
> If so and it builds you can merge it
> if not, I need to build it and check

@lauranovich no, I didn't, and don't have much time currently. If you have it, please do. It will help me a lot!

**Comment by lauranovich** [comment]
Screenshot from 2020-09-30 18-19-40
I am not seeing the formatted page when I try to access a page that doesn't exist

**Comment by dgarcia360** [comment]
@lauranovich https://github.com/scylladb/scylla-monitoring/pull/1068#issuecomment-701460901

**Comment by lauranovich** [comment]
@dgarcia360 - https://github.com/scylladb/scylla-monitoring/pull/1068#issuecomment-701933002

**Comment by dgarcia360** [comment]
@lauranovich I think this PR can be merged.

**Pull request merged**
