### PR TITLE
Assignment 

### PR DESCRIPTION
**Pull request by annastuchlik**
I've improved this document as part of my assignment in the recruitment process.

### CODE REVIEW

**Comment by tzach** [comment]
@raoufchebri can you please review?

**Review by raoufchebri — APPROVED** [review]

**Comment by tzach** [comment]
@annastuchlik can you please resend the PR or fix the conflicts?

**Comment by tzach** [comment]
@annastuchlik can you please resend the PR or fix the conflicts?

**Comment by annastuchlik** [comment]
The fork was deleted, so I've applied the changes here: https://github.com/scylladb/care-pet/pull/66.
I'm closing this PR.

**Pull request closed without merging**
