### PR TITLE
update care pet home page

### PR DESCRIPTION
**Pull request by raoufchebri**

### CODE REVIEW

**Comment by raoufchebri** [comment]
Updated the page title and description for a more generic-non-scylla-centric purpose
Screenshot from 2022-01-20 15-52-47

The 3 language-specific boxes redirect to the getting started page. The goal to change the url to a language-specific page (TBD).

**Comment by tzach** [comment]
@raoufchebri for your next PR, better create a branch in your fork, push to it, and send PR
Avoid pushing to master

**Comment by raoufchebri** [comment]
@tzach good idea. Let's do that. I prefer to have it in another branch too.

**Comment by tzach** [comment]
I like the design, but its look like all links (Go, Java, Rust) leads to the same generic page for now

**Comment by raoufchebri** [comment]
Yes, correct. The next step is to link the go link to the Go pages.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tzach** [comment]
> Yes, correct. The next step is to link the go link to the Go pages.

I will wait with the merge till the links are useful.
As a start, you can link them to the relevant Github pages, and update the links in a following PR.

**Comment by raoufchebri** [comment]
@tzach, I linked them with Scylla U pages for each respective language. I can link the Go page to the `build with go` page on care-pet after #52 is merged.

**Pull request merged**
